### ISSUE TITLE
Система ролей в командах

### ISSUE THREAD

**Issue by MWGuy** [manga-application/bugtracker#4]

**Comment by gou177** [comment]
RBAC по дб
- (:Role {label: "...", permissions: ["create", "..."]})
- (:Team) -[:OWN_ROLE]-> (:Role)
- (:User) -[:HAS_ROLE]-> (:Role)

**Comment by land47** [comment]
закажите мне пиццу

**Comment by land47** [comment]
закажите мне пиццу
