### ISSUE TITLE
Лента с обновлениями тайтлов

### ISSUE THREAD

**Issue by blinddude7489** [manga-application/bugtracker#6]
До сих пор не понимаю, как люди находят тайтлы, которыми занимается моя команда. Возможно, это из-за ленты со случайными тайтлами. Но толку от неё мало.
Тайтлы с новыми главами могут находиться в ленте 24 часа. Благодаря этому больше человек узнает о тайтле.
В один блок с названием тайтла можно впихнуть номер главы.

**Comment by MWGuy** [comment]
Сделаем
